language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - whoami
  - pwd
  - ls
  - git status
  - ls ~
  - echo $HOME
  - env
  - cd
  - (git clone https://github.com/xianyi/OpenBLAS && cd OpenBLAS && make -j 4 && sudo make install)
  - ls /opt/OpenBLAS/lib
  - git clone https://github.com/torch/distro.git ~/torch --recursive
  - cd ~/torch; ./install.sh
  - mkdir ~/git
  - cd ~/git
  - cd ~/build/hughperkins/cltorch

script:
  - echo hello
  - source ~/torch/install/bin/torch-activate
  - env
  - mkdir build
  - cd build
  - cmake ..
  - make -j 4

notifications:
  email:
    on_success: never
    on_failure: never

